version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    image: coreytrombley/parsley:1.0.0
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - migration
      - db
