# Generated by Django 2.0.1 on 2018-01-31 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_phone'),
        ('phone', '0002_auto_20180131_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='patient.Patient'),
            preserve_default=False,
        ),
    ]
