# Generated by Django 2.0.1 on 2018-01-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='terms_accpeted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
