# Generated by Django 2.0.1 on 2018-01-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180131_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='terms_accpeted_at',
            new_name='terms_accepted_at',
        ),
    ]
