# Generated by Django 2.0.1 on 2018-01-31 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20180131_2148'),
        ('patient', '0003_auto_20180131_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phone.Phone'),
            preserve_default=False,
        ),
    ]
